dist: bionic
language: c
services:
  - docker

stages:
  - name: Code quality, linting, syntax, code style

jobs:
  include:
    - stage: Code quality, linting, syntax, code style

      name: Run shellchecking on BASH
      script: echo test
