dist: bionic
language: c
services:
  - docker

matrix:
  allow_failures:
    - env: ALLOW_SOFT_FAILURE_HERE=true

stages:
  - name: Code quality, linting, syntax, code style

jobs:
  include:
    - stage: Code quality, linting, syntax, code style

      name: Run shellchecking on BASH
      script: echo test
